import {ThemeConfig} from '../models'

export const defaultThemeConfig = {
  referenceDevice: {
    width: 390,
    height: 844,
  },
  colors: {
    // PRIMARY
    primary: 'rgba(0, 169, 206, 1)',
    secondary: 'rgba(255, 199, 44, 1)',
    'grey-900': 'rgba(34, 63, 70, 1)',
    'grey-800': 'rgba(61, 88, 94, 1)',
    'grey-200': 'rgba(161, 173, 175, 1)',
    'grey-100': 'rgba(234, 239, 240, 1)',
    white: 'rgba(255, 255, 255, 1)',
    black: 'rgba(17, 17, 17, 1)',

    // SEMANTIC
    danger: 'rgba(246, 83, 83, 1)',
    success: 'rgba(63, 182, 24, 1)',
    info: 'rgba(63, 182, 210, 1)',
    warning: 'rgba(255, 117, 24, 1)',
    mint: 'rgba(32, 150, 110, 1)',

    'success-notification': 'rgba(72, 193, 181, 1)',
    'danger-notification': 'rgba(209, 94, 83, 1)',
    'warning-notification': 'rgba(255, 173, 50, 1)',
    'info-notification': 'rgba(77, 175, 234, 1)',

    // NEUTRAL/ALPHA
    'neutral-alpha-900': 'rgba(34, 63, 70, 0.9)',
    'neutral-alpha-700': 'rgba(34, 63, 70, 0.75)',
    'neutral-alpha-400': 'rgba(34, 63, 70, 0.40)',
    'neutral-alpha-300': 'rgba(34, 63, 70, 0.30)',
    'neutral-alpha-200': 'rgba(34, 63, 70, 0.15)',
    'neutral-alpha-100': 'rgba(34, 63, 70, 0.10)',
    'neutral-shadow-300': 'rgba(6, 14, 16, 0.30)',

    'neutral-red-alpha-300': 'rgba(228, 65, 96, 0.30)',
    'neutral-green-alpha-300': 'rgba(68, 238, 162, 0.30)',
    'neutral-grey-alpha-200': 'rgba(234, 239, 240, 0.15)',
    'neutral-blue-soft': 'rgba(130, 222, 243, 1)',
    'neutral-blue-alpha': 'rgba(99, 115, 129, 1)',

    // GRADIENT
    'primary-outline': 'transparent',
    'secondary-outline': 'transparent',
    'success-outline': 'transparent',
    'info-outline': 'transparent',
    'warning-outline': 'transparent',
    'danger-outline': 'transparent',
    'white-outline': 'transparent',

    // SEPERATOR COLOR
    'seperator-grey-200': 'rgba(79, 100, 104, 1)',

    transparent: 'rgba(0, 0, 0, 0)',
  },
  options: {
    hasNotch: false,
    hasDynamicIsland: false,
    language: {
      name: 'en-US',
    },
  },
  images: {
    // @generated-start:images
    '064-check': require('../assets/images/commonIcon/064-check.png'),
    '1': require('../assets/images/story/1.png'),
    '2': require('../assets/images/story/2.png'),
    '3': require('../assets/images/story/3.png'),
    '4': require('../assets/images/story/4.png'),
    account: require('../assets/images/card/account.png'),
    'appointment-icon': require('../assets/images/entry/appointment-icon.png'),
    'atm-icon': require('../assets/images/entry/atm-icon.png'),
    'card-check': require('../assets/images/empty-state/card-check.png'),
    'card-error-1': require('../assets/images/empty-state/card-error-1.png'),
    'card-error-2': require('../assets/images/empty-state/card-error-2.png'),
    'card-error-icon': require('../assets/images/commonIcon/card-error-icon.png'),
    'card-info': require('../assets/images/empty-state/card-info.png'),
    'card-warning': require('../assets/images/empty-state/card-warning.png'),
    'check-active': require('../assets/images/commonIcon/check-active.png'),
    'check-passive': require('../assets/images/commonIcon/check-passive.png'),
    clear: require('../assets/images/commonIcon/clear.png'),
    close: require('../assets/images/commonIcon/close.png'),
    copy: require('../assets/images/commonIcon/copy.png'),
    'credit-card': require('../assets/images/empty-state/credit-card.png'),
    'credit-card-light': require('../assets/images/empty-state/credit-card-light.png'),
    'dashboard-bg': require('../assets/images/dashboard/dashboard-bg.png'),
    date: require('../assets/images/result/date.png'),
    debit: require('../assets/images/card/debit.png'),
    'direction-right': require('../assets/images/icons/direction-right.png'),
    document: require('../assets/images/empty-state/document.png'),
    'document-info': require('../assets/images/empty-state/document-info.png'),
    'dummy-profile': require('../assets/images/entry/dummy-profile.png'),
    'eye-active': require('../assets/images/commonIcon/eye-active.png'),
    'eye-passive': require('../assets/images/commonIcon/eye-passive.png'),
    fast: require('../assets/images/logo/fast.png'),
    'fast-tcmb': require('../assets/images/fast/fast-tcmb.png'),
    'general-alert': require('../assets/images/empty-state/general-alert.png'),
    'general-check': require('../assets/images/empty-state/general-check.png'),
    'general-info': require('../assets/images/empty-state/general-info.png'),
    'general-search': require('../assets/images/empty-state/general-search.png'),
    'general-warning': require('../assets/images/empty-state/general-warning.png'),
    'gradient-bg': require('../assets/images/splash/gradient-bg.png'),
    hgs: require('../assets/images/result/hgs.png'),
    'hgs-logo': require('../assets/images/logo/hgs-logo.png'),
    'hgs-logo-white': require('../assets/images/logo/hgs-logo-white.png'),
    'info-icon': require('../assets/images/commonIcon/info-icon.png'),
    'kampanya-slider-mini-1': require('../assets/images/story/kampanya-slider-mini-1.png'),
    'left-arrow-icon': require('../assets/images/commonIcon/left-arrow-icon.png'),
    line: require('../assets/images/commonIcon/line.png'),
    'list-error-empty-state': require('../assets/images/empty-state/list-error-empty-state.png'),
    'location-icon': require('../assets/images/entry/location-icon.png'),
    maestro: require('../assets/images/card/cardBrand/maestro.png'),
    'master-card': require('../assets/images/card/cardBrand/master-card.png'),
    menu: require('../assets/images/commonIcon/menu.png'),
    microphone: require('../assets/images/commonIcon/microphone.png'),
    'mobile-locked': require('../assets/images/empty-state/mobile-locked.png'),
    'money-transfer-1': require('../assets/images/empty-state/money-transfer-1.png'),
    'money-transfer-1-light': require('../assets/images/empty-state/money-transfer-1-light.png'),
    'money-transfer-2': require('../assets/images/empty-state/money-transfer-2.png'),
    'money-transfer-3': require('../assets/images/empty-state/money-transfer-3.png'),
    'money-transfer-icon': require('../assets/images/commonIcon/money-transfer-icon.png'),
    more: require('../assets/images/commonIcon/more.png'),
    'more-icon': require('../assets/images/entry/more-icon.png'),
    'near-atm': require('../assets/images/nearPtt/near-atm.png'),
    'near-branch': require('../assets/images/nearPtt/near-branch.png'),
    'near-building': require('../assets/images/nearPtt/near-building.png'),
    'no-address': require('../assets/images/empty-state/no-address.png'),
    'no-internet': require('../assets/images/empty-state/no-internet.png'),
    notification: require('../assets/images/notifications/notification.png'),
    'notification-icon': require('../assets/images/entry/notification-icon.png'),
    'notification-locked': require('../assets/images/notifications/notification-locked.png'),
    notificationEmpty: require('../assets/images/result/notificationEmpty.png'),
    notifications: require('../assets/images/empty-state/notifications.png'),
    ok: require('../assets/images/result/ok.png'),
    'onboarding-1': require('../assets/images/onBoarding/onboarding-1.png'),
    'onboarding-2': require('../assets/images/onBoarding/onboarding-2.png'),
    'onboarding-3': require('../assets/images/onBoarding/onboarding-3.png'),
    person: require('../assets/images/entry/person.png'),
    phone: require('../assets/images/empty-state/phone.png'),
    'phone-icon': require('../assets/images/entry/phone-icon.png'),
    pos: require('../assets/images/entry/pos.png'),
    profile: require('../assets/images/commonIcon/profile.png'),
    'pttbank-black': require('../assets/images/logo/pttbank-black.png'),
    'pttbank-black-colored': require('../assets/images/logo/pttbank-black-colored.png'),
    'pttbank-white': require('../assets/images/logo/pttbank-white.png'),
    'qr-background-blur': require('../assets/images/qr/qr-background-blur.png'),
    'qr-button': require('../assets/images/logo/qr-button.png'),
    'qr-code': require('../assets/images/commonIcon/qr-code.png'),
    qrcode: require('../assets/images/commonIcon/qrcode.png'),
    'question-mark': require('../assets/images/commonIcon/question-mark.png'),
    'radio-off': require('../assets/images/commonIcon/radio-off.png'),
    'radio-on': require('../assets/images/commonIcon/radio-on.png'),
    'right-arrow-icon': require('../assets/images/commonIcon/right-arrow-icon.png'),
    'sad-face': require('../assets/images/entry/sad-face.png'),
    search: require('../assets/images/commonIcon/search.png'),
    send: require('../assets/images/commonIcon/send.png'),
    settings: require('../assets/images/commonIcon/settings.png'),
    shortcut: require('../assets/images/commonIcon/shortcut.png'),
    'smiley-face': require('../assets/images/entry/smiley-face.png'),
    social: require('../assets/images/card/social.png'),
    'social-help-icon': require('../assets/images/entry/social-help-icon.png'),
    star: require('../assets/images/commonIcon/star.png'),
    'star-solid': require('../assets/images/commonIcon/star-solid.png'),
    transactionsEmpty: require('../assets/images/result/transactionsEmpty.png'),
    troy: require('../assets/images/card/cardBrand/troy.png'),
    'unlock-password': require('../assets/images/empty-state/unlock-password.png'),
    visa: require('../assets/images/card/cardBrand/visa.png'),
    'warning-error': require('../assets/images/commonIcon/warning-error.png'),

    // @generated-end:images
  },
  icons: {
    // @generated-start:icons
    'about-phone': require('../assets/icons/svg/interface/about-phone.svg'),
    'account-activite': require('../assets/icons/svg/interface/account-activite.svg'),
    'add-circle': require('../assets/icons/svg/interface/add-circle.svg'),
    'alarm-check': require('../assets/icons/svg/interface/alarm-check.svg'),
    amblem: require('../assets/icons/svg/menu/amblem.svg'),
    'amblem-two': require('../assets/icons/svg/menu/amblem-two.svg'),
    'arrow-down': require('../assets/icons/svg/interface/arrow-down.svg'),
    'arrow-left': require('../assets/icons/svg/interface/arrow-left.svg'),
    'arrow-right': require('../assets/icons/svg/interface/arrow-right.svg'),
    'arrow-share': require('../assets/icons/svg/interface/arrow-share.svg'),
    'arrow-transfer': require('../assets/icons/svg/interface/arrow-transfer.svg'),
    banking: require('../assets/icons/svg/interface/banking.svg'),
    bill: require('../assets/icons/svg/interface/bill.svg'),
    'bulleted-list': require('../assets/icons/svg/interface/bulleted-list.svg'),
    burgermenu: require('../assets/icons/svg/interface/burgermenu.svg'),
    calendar: require('../assets/icons/svg/interface/calendar.svg'),
    'calendar-delete': require('../assets/icons/svg/interface/calendar-delete.svg'),
    calling: require('../assets/icons/svg/interface/calling.svg'),
    camera: require('../assets/icons/svg/interface/camera.svg'),
    'car-time': require('../assets/icons/svg/interface/car-time.svg'),
    'card-user': require('../assets/icons/svg/interface/card-user.svg'),
    'check-circle': require('../assets/icons/svg/interface/check-circle.svg'),
    'check-fill': require('../assets/icons/svg/notification/check-fill.svg'),
    'chevron-left': require('../assets/icons/svg/interface/chevron-left.svg'),
    'chevron-right': require('../assets/icons/svg/interface/chevron-right.svg'),
    'circle-help': require('../assets/icons/svg/interface/circle-help.svg'),
    copy: require('../assets/icons/svg/interface/copy.svg'),
    'copy-check': require('../assets/icons/svg/interface/copy-check.svg'),
    'credit-card': require('../assets/icons/svg/interface/credit-card.svg'),
    ellipse: require('../assets/icons/svg/notification/ellipse.svg'),
    euro: require('../assets/icons/svg/currency/euro.svg'),
    'external-link': require('../assets/icons/svg/interface/external-link.svg'),
    eye: require('../assets/icons/svg/interface/eye.svg'),
    'eye-disable': require('../assets/icons/svg/interface/eye-disable.svg'),
    'fast-delivery': require('../assets/icons/svg/interface/fast-delivery.svg'),
    'fast-icon': require('../assets/icons/svg/interface/fast-icon.svg'),
    filter: require('../assets/icons/svg/interface/filter.svg'),
    gallery: require('../assets/icons/svg/interface/gallery.svg'),
    gbp: require('../assets/icons/svg/currency/gbp.svg'),
    Global: require('../assets/icons/svg/licensePlates/Global.svg'),
    help: require('../assets/icons/svg/interface/help.svg'),
    hgs: require('../assets/icons/svg/interface/hgs.svg'),
    'hgs-o': require('../assets/icons/svg/interface/hgs-o.svg'),
    'id-card': require('../assets/icons/svg/interface/id-card.svg'),
    information: require('../assets/icons/svg/interface/information.svg'),
    'information-circle': require('../assets/icons/svg/interface/information-circle.svg'),
    'information-fill': require('../assets/icons/svg/notification/information-fill.svg'),
    line: require('../assets/icons/svg/interface/line.svg'),
    loading: require('../assets/icons/svg/interface/loading.svg'),
    location: require('../assets/icons/svg/interface/location.svg'),
    'location-map': require('../assets/icons/svg/interface/location-map.svg'),
    lock: require('../assets/icons/svg/interface/lock.svg'),
    mail: require('../assets/icons/svg/interface/mail.svg'),
    'menu-abroad': require('../assets/icons/svg/menu/menu-abroad.svg'),
    'menu-car': require('../assets/icons/svg/menu/menu-car.svg'),
    'menu-card-i': require('../assets/icons/svg/menu/menu-card-i.svg'),
    'menu-circle-test': require('../assets/icons/svg/menu/menu-circle-test.svg'),
    'menu-circle-vertical': require('../assets/icons/svg/interface/menu-circle-vertical.svg'),
    'menu-document-text': require('../assets/icons/svg/menu/menu-document-text.svg'),
    'menu-donate': require('../assets/icons/svg/menu/menu-donate.svg'),
    'menu-dot': require('../assets/icons/svg/interface/menu-dot.svg'),
    'menu-exit': require('../assets/icons/svg/menu/menu-exit.svg'),
    'menu-hgs': require('../assets/icons/svg/menu/menu-hgs.svg'),
    'menu-line-horizontal': require('../assets/icons/svg/interface/menu-line-horizontal.svg'),
    'menu-money-add': require('../assets/icons/svg/menu/menu-money-add.svg'),
    'menu-money-transfer': require('../assets/icons/svg/menu/menu-money-transfer.svg'),
    'menu-oldies': require('../assets/icons/svg/menu/menu-oldies.svg'),
    'menu-placeholder': require('../assets/icons/svg/menu/menu-placeholder.svg'),
    'menu-qrscan': require('../assets/icons/svg/menu/menu-qrscan.svg'),
    'menu-shield': require('../assets/icons/svg/menu/menu-shield.svg'),
    'menu-wallet': require('../assets/icons/svg/menu/menu-wallet.svg'),
    minus: require('../assets/icons/svg/interface/minus.svg'),
    'mobile-payment': require('../assets/icons/svg/interface/mobile-payment.svg'),
    'money-add': require('../assets/icons/svg/interface/money-add.svg'),
    'money-arrow-right': require('../assets/icons/svg/interface/money-arrow-right.svg'),
    'money-check': require('../assets/icons/svg/interface/money-check.svg'),
    'money-coin': require('../assets/icons/svg/interface/money-coin.svg'),
    'money-remove': require('../assets/icons/svg/interface/money-remove.svg'),
    'money-transfer': require('../assets/icons/svg/interface/money-transfer.svg'),
    'money-user': require('../assets/icons/svg/interface/money-user.svg'),
    'near-bulleted-list': require('../assets/icons/svg/nearPtt/near-bulleted-list.svg'),
    'near-map': require('../assets/icons/svg/nearPtt/near-map.svg'),
    notification: require('../assets/icons/svg/interface/notification.svg'),
    'packaging-location': require('../assets/icons/svg/interface/packaging-location.svg'),
    'phone-book': require('../assets/icons/svg/interface/phone-book.svg'),
    plus: require('../assets/icons/svg/interface/plus.svg'),
    'plus-circle-remove': require('../assets/icons/svg/interface/plus-circle-remove.svg'),
    qr: require('../assets/icons/svg/interface/qr.svg'),
    'qr-alternative': require('../assets/icons/svg/interface/qr-alternative.svg'),
    'qr-iban': require('../assets/icons/svg/interface/qr-iban.svg'),
    'qr-menu': require('../assets/icons/svg/interface/qr-menu.svg'),
    'qr-transfer': require('../assets/icons/svg/interface/qr-transfer.svg'),
    refresh: require('../assets/icons/svg/interface/refresh.svg'),
    remove: require('../assets/icons/svg/interface/remove.svg'),
    'remove-big': require('../assets/icons/svg/interface/remove-big.svg'),
    'remove-circle': require('../assets/icons/svg/interface/remove-circle.svg'),
    search: require('../assets/icons/svg/interface/search.svg'),
    sendmoney: require('../assets/icons/svg/interface/sendmoney.svg'),
    settings: require('../assets/icons/svg/interface/settings.svg'),
    share: require('../assets/icons/svg/interface/share.svg'),
    'share-rectangle': require('../assets/icons/svg/interface/share-rectangle.svg'),
    'social-asist': require('../assets/icons/svg/interface/social-asist.svg'),
    star: require('../assets/icons/svg/interface/star.svg'),
    'star-fill': require('../assets/icons/svg/interface/star-fill.svg'),
    tick: require('../assets/icons/svg/interface/tick.svg'),
    tl: require('../assets/icons/svg/currency/tl.svg'),
    TR: require('../assets/icons/svg/licensePlates/TR.svg'),
    'transfer-two': require('../assets/icons/svg/interface/transfer-two.svg'),
    usd: require('../assets/icons/svg/currency/usd.svg'),
    user: require('../assets/icons/svg/interface/user.svg'),
    'vibrate-mode': require('../assets/icons/svg/interface/vibrate-mode.svg'),
    'warning-circle': require('../assets/icons/svg/interface/warning-circle.svg'),
    'warning-error': require('../assets/icons/svg/interface/warning-error.svg'),

    // @generated-end:icons
  },
  fontSizes: {
    xs: 10,
    sm: 12,
    md: 14,
    lg: 16,
    xl: 18,
    '2xl': 24,
    '3xl': 36,
  },
  fontFamilies: {
    Markpro: 'Markpro',
    'Markpro-Black': 'Markpro-Black',
    'Markpro-Bold': 'Markpro-Bold',
    'Markpro-Book': 'Markpro-Book',
    'Markpro-ExtraLight': 'Markpro-ExtraLight',
    'Markpro-Heavy': 'Markpro-Heavy',
    'Markpro-Light': 'Markpro-Light',
    'Markpro-Medium': 'Markpro-Medium',
    'Markpro-Regular': 'Markpro-Regular',
    'Markpro-SemiBold': 'Markpro-SemiBold',
    'Markpro-Thin': 'Markpro-Thin',
  },
  fontWeights: {
    'Markpro-Black': '900',
    'Markpro-Bold': '700',
    'Markpro-Book': '500',
    'Markpro-ExtraLight': '200',
    'Markpro-Heavy': '800',
    'Markpro-Light': '300',
    'Markpro-Medium': '500',
    'Markpro-Regular': '400',
    'Markpro-SemiBold': '600',
    'Markpro-Thin': '100',
  },
  goBack: () => {},
} as const satisfies ThemeConfig
