/**
 * Empty interfaces for module augmentation.
 * Consumer projects extend these via withRottAssets() generated .d.ts files.
 *
 * @example
 * // Auto-generated by withRottAssets() in .rott/consumer-assets.d.ts:
 * declare module '@tansuk/rott-ui' {
 *   interface ConsumerImageKeys { 'my-image': true }
 *   interface ConsumerIconKeys { 'my-icon': true }
 * }
 */
// eslint-disable-next-line @typescript-eslint/no-empty-interface
export interface ConsumerImageKeys {}
// eslint-disable-next-line @typescript-eslint/no-empty-interface
export interface ConsumerIconKeys {}
